name: Test Email Notification

on:
  workflow_dispatch:  # Allows manual triggering only

jobs:
  test-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smtplib
          
      - name: Run email test
        run: python test_email.py
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }} 